### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'env' with webassets 0.10

### ISSUE THREAD

**Issue by keitheis** [sontek/pyramid_webassets#45]
Just found one issue with webassets 0.10. It works fine with webassets 0.9.

```
  File "./virtualenvs/34/lib/python3.4/site-packages/pyramid/config/__init__.py", line 755, in include
    c(configurator)
  File "./uest/Python/pyramid_webassets/pyramid_webassets/__init__.py", line 286, in includeme
    assets_env = get_webassets_env_from_settings(config.registry.settings)
  File "./uest/Python/pyramid_webassets/pyramid_webassets/__init__.py", line 222, in get_webassets_env_from_settings
    assets_env = Environment(asset_dir, asset_url, **kwargs)
  File "./virtualenvs/34/lib/python3.4/site-packages/webassets/env.py", line 750, in __init__
    super(Environment, self).__init__(**more_config)
  File "./virtualenvs/34/lib/python3.4/site-packages/webassets/env.py", line 707, in __init__
    self.config.setdefault('resolver', self.resolver_class())
TypeError: __init__() missing 1 required positional argument: 'env'
```
